# Generated by Django 4.0.4 on 2022-05-05 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0039_orderproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproduct",
            name="static_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Фиксированная стоимость",
                blank=True,
            ),
            preserve_default=False,
        ),
    ]
