# Generated by Django 4.0.4 on 2022-05-11 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20220505_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Новый'), (1, 'Подтвержден'), (2, 'Готовка'), (3, 'Доставка'), (4, 'Выполнен')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='static_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Фиксированная стоимость'),
        ),
    ]
