# Generated by Django 4.0.4 on 2022-05-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_order_status_alter_orderproduct_static_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='комментарий'),
        ),
    ]
