# Generated by Django 4.0.4 on 2022-05-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_order_called_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.PositiveSmallIntegerField(choices=[(0, 'карта'), (1, 'наличные')], db_index=True, default=1),
        ),
    ]
