# Generated by Django 4.0.4 on 2022-05-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_alter_orderproduct_order_alter_orderproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.PositiveSmallIntegerField(choices=[(0, 'карта'), (1, 'наличные')], db_index=True, default=0),
        ),
    ]
